[package]
name = "timebar"
description = "Cli to get some time progress bars on a terminal."
license = "MIT"
version = "0.1.0"
authors = ["Sung Kwon <mailtosungkwon@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
termion = "1.5.5"
